# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
target 'firebaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseApp

  target 'firebaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'firebaseApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseApp-tvOS

#   target 'firebaseApp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
